dist: bionic
sudo: false
services:
    - postgresql
addons:
    postgresql: "11"
language: python
python:
    - "3.5" # Required for Debian Stretch support
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - pip install --upgrade pip
    - pip install pipenv
    - pipenv lock
    - pipenv install --dev
before_script:
    - psql --version
    - psql -U postgres -c 'SELECT version();'
    - psql -c 'create database serveradmin owner travis;' -U postgres
    - psql -c 'create database powerdns owner travis;' -U postgres
    - cp serveradmin/local_settings.py.travis.py serveradmin/local_settings.py
    - python -m serveradmin migrate
script:
    # This will use Python's standard unit test discovery feature.
    - python -m unittest discover adminapi -v
    - python -Wall -m serveradmin test --noinput --parallel
    # Build sphinx docs, error on warning
    - cd docs
    - SPHINXOPTS='-W' make html
